### ISSUE TITLE
Error: No such command "device"

### ISSUE THREAD

**Issue by IonutQo2** [platformio/platformio-examples#11]
Hello,

I have just installed PlatformIO trying to use this software instead of INO.
Though, when I run the command: **platformio device list** I get the following output:
```
Usage: platformio [OPTIONS] COMMAND [ARGS]...

Error: No such command "device"
```
My platformio version is: 3.3.0a7
Has someone had similar problems?

Thank you.

**Comment by ivankravets** [comment]
Please report to https://community.platformio.org
