### ISSUE TITLE
Compiling static libs for local environment

### ISSUE THREAD

**Issue by nick-benoit14** [platformio/platformio-examples#2]
I was transitioning an existing platformio v2 project to v3, and attempting to add some tests as I went, and I was only able to include static libraries from the lib folder after changing the name of our main file form `our_project_name.ino` to `main.cpp`. I didn't see any mention of the name of your main file anywhere affecting linking to static libraries. 

Is this an issue, or was I just setting something up incorrectly? 
I am on a mac with OSX El Capitan v 10.11.4.

**Comment by ivankravets** [comment]
Please post you question here https://community.platformio.org
