### ISSUE TITLE
Wifi Scan

### ISSUE THREAD

**Issue by totovr** [platformio/platformio-examples#22]
Good afternoon, I'm trying to set the esp32 in PlataformIO but when I tried to run the WIFI scan program that comes in the example shared me the next error.

![screen shot 2017-11-01 at 15 19 43](https://user-images.githubusercontent.com/15333235/32262459-1f597eac-bf18-11e7-9406-118dd5c7bda7.png)

**Comment by ivankravets** [comment]
Does it work with the latest version of PIO Core?

**Comment by ivankravets** [comment]
Please reopen if you still need help
