### ISSUE TITLE
F1 libs are unusable

### ISSUE THREAD

**Issue by alm494** [platformio/platformio-examples#25]
Hi! Tried yor STM32 HAL cube examples and they are compiling excellent for the default board 'nucleo_f401re'.
But right after I've changed the target board to 'genericSTM32F103CB' with build_flags = -DF1 the build fails with a lot of library errors. The most weird is that uint_8 and similar types are not recognized because of stdint.h is not linked.
Also I noticed there is a newer HAL library version 1.6.0 available for F1 family since May 17, 2017 but Platformio delivers old version 1.4.0

**Comment by ivankravets** [comment]
Please move your issue to https://github.com/platformio/platform-ststm32/issues

Also, please create a new issue with a request to update STM32HAL to 1.6.0
