### ISSUE TITLE
Question of debug Unit testing program.

### ISSUE THREAD

**Issue by ysong-aceinna** [platformio/platformio-examples#39]
Hi, I want to debug the Unit testing program 'unit-testing/calculator/', what I did is click the 'Pre-Debug' button under 'env:native', and got a feedback 'Error: Please setup environments in `platformio.ini` file'.
Could you please tell me how to setup environments in `platformio.ini' to fix this? Thank you!

![image](https://user-images.githubusercontent.com/37057411/89618544-ec6a5980-d8be-11ea-83b7-bee78e5b4367.png)

**Comment by ivankravets** [comment]
There is a feature request for this https://github.com/platformio/platformio-core/issues/948

We plan to implement this soon.

**Comment by lfenster** [comment]
has this been implemented yet?

**Comment by ysong-aceinna** [comment]
> has this been implemented yet?

No :(
