### ISSUE TITLE
Potential null pointer dereference in interrupt handler

### ISSUE THREAD

**Issue by wjqsec** [platformio/platformio-examples#44]
In timer_irq_handler and rt_systick. The values os_tsk and TimMasterHandle might be zero and then dereferenced

**Comment by valeros** [comment]
Hi @XinDistance, could you please point out where exactly the vulnerable code is located in this repository?

**Comment by wjqsec** [comment]
I see, this might not come from the source code here but from the platform source code.

**Comment by valeros** [comment]
> I see, this might not come from the source code here but from the platform source code

What platform  do you mean?

**Comment by ivankravets** [comment]
Please find an example in the https://github.com/topics/platformio-platform and report a new issue.

**Comment by wjqsec** [comment]
I need further investigations. Still didn't figure out where the root reason is.
