### ISSUE TITLE
Esp8266 OTA - No answer after sending invitation

### ISSUE THREAD

**Issue by tiestvangool** [platformio/platformio-examples#9]
Hi GitHub Community,

I am working on enabling OTA on the esp8266 micro controller. I have setup all prerequisites, can compile the firmware and upload using USB cable successfully.
I have identified the IP address for the device using pio device monitor -b 115200.
Upon issuing the following command: pio run -e nodemcuv2 -t upload --upload-port 192.168.1.10 I get stuck after sending the invitation and do not receive a response from the device, see log below.
I found references of this problem here: https://www.penninkhof.com/2015/12/1610-over-the-air-esp8266-programming-using-platformio/ but was not able to turn this into a resolution.
Has anyone ran into this issue and how did you resolve this?

I have Linux/Ubuntu machine and my network router is NetGear.

Thanks in advance for any guidance,
-Tiest

[Sat Jan 7 13:12:55 2017] Processing nodemcuv2 (platform: espressif8266, board: nodemcuv2, framework: arduino)
Verbose mode can be enabled via -v, --verbose option
Collected 24 compatible libraries
Looking for dependencies...
Library Dependency Graph
|-- 
| |-- v1.0
| |-- 
| | |-- v1.0
|-- 
| |-- v1.0
|-- v1.0
Looking for upload port...
Use manually specified: 192.168.1.10
Uploading .pioenvs/nodemcuv2/firmware.bin
13:12:56 [DEBUG]: Options: {'esp_ip': '192.168.1.10', 'host_port': 21165, 'image': '.pioenvs/nodemcuv2/firmware.bin', 'host_ip': '0.0.0.0', 'auth': '', 'esp_port': 8266, 'spiffs': False, 'debug': True, 'progress': True}
13:12:56 [INFO]: Starting on 0.0.0.0:21165
13:12:56 [INFO]: Upload size: 247776
13:12:56 [INFO]: Sending invitation to: 192.168.1.10
13:13:06 [ERROR]: No Answer
*** [upload] Error 1
========================== [ERROR] Took 10.98 seconds ==========================

**Comment by ivankravets** [comment]
Please move this question here

* http://community.platformio.org/
